//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolloAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abono
    {
        public int abonoId { get; set; }
        public int facturaId { get; set; }
        public decimal montoPorPagar { get; set; }
        public int cuotasPendientes { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fechaSigPago { get; set; }
        public decimal montoPorMora { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
